-- Inserindo 100 tarefas de exemplo no banco de dados `tarefas`

USE `tarefas`;

INSERT INTO `tarefas` (`titulo`, `descricao`, `prazo`, `concluido`, `id_funcionario`) VALUES
('Desenvolver a API de autenticação', 'Criar os endpoints para login, registro e logout de usuários.', DATE_ADD(CURDATE(), INTERVAL 10 DAY), 1, 2),
('Modelar o banco de dados para o novo módulo', 'Desenhar o esquema do banco de dados para o módulo de gerenciamento de projetos.', DATE_ADD(CURDATE(), INTERVAL 15 DAY), 0, 3),
('Corrigir bug no layout responsivo do dashboard', 'O menu lateral está quebrando em telas menores que 768px.', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 0, 1),
('Implementar o fluxo de recuperação de senha', 'Desenvolver o processo de envio de email com link para reset de senha.', DATE_ADD(CURDATE(), INTERVAL 5 DAY), 0, 2),
('Pesquisar bibliotecas de gráficos para o relatório', 'Analisar Chart.js, D3.js e Highcharts para exibir os dados de vendas.', DATE_ADD(CURDATE(), INTERVAL 3 DAY), 1, 3),
('Configurar o ambiente de testes (staging)', 'Provisionar o servidor e configurar o deploy automático para o ambiente de staging.', DATE_ADD(CURDATE(), INTERVAL 7 DAY), 0, 1),
('Escrever a documentação da API', 'Utilizar o formato OpenAPI (Swagger) para documentar todos os endpoints.', DATE_ADD(CURDATE(), INTERVAL 20 DAY), 0, 2),
('Otimizar as consultas ao banco de dados', 'Analisar e otimizar as queries mais lentas identificadas no último relatório de performance.', DATE_ADD(CURDATE(), INTERVAL 8 DAY), 0, 3),
('Criar a interface de upload de arquivos', 'Desenvolver o front-end e o back-end para o upload de imagens de perfil.', DATE_ADD(CURDATE(), INTERVAL 12 DAY), 1, 1),
('Reunião de planejamento da Sprint 5', 'Definir as prioridades e tarefas para a próxima sprint com a equipe.', DATE_ADD(CURDATE(), INTERVAL 1 DAY), 1, 2),
('Atualizar as dependências do projeto', 'Verificar e atualizar todas as bibliotecas e frameworks para as versões mais recentes.', DATE_ADD(CURDATE(), INTERVAL 4 DAY), 0, 3),
('Refatorar o serviço de notificações', 'Separar a lógica de envio de email e push notification em classes distintas.', DATE_ADD(CURDATE(), INTERVAL 18 DAY), 0, 1),
('Testar a integração com o gateway de pagamento', 'Realizar testes de ponta a ponta no fluxo de pagamento com cartão de crédito.', DATE_ADD(CURDATE(), INTERVAL 6 DAY), 0, 2),
('Criar os testes unitários para o módulo de usuários', 'Garantir a cobertura de no mínimo 80% dos testes para a classe User.', DATE_ADD(CURDATE(), INTERVAL 14 DAY), 0, 3),
('Apresentar a demo do novo recurso para os stakeholders', 'Preparar e realizar a apresentação do módulo de relatórios.', DATE_ADD(CURDATE(), INTERVAL 9 DAY), 0, 1),
('Configurar o cache para a lista de produtos', 'Implementar cache com Redis para a página principal de produtos.', DATE_ADD(CURDATE(), INTERVAL 11 DAY), 1, 2),
('Revisar o código do pull request #123', 'Fazer o code review do novo recurso de exportação de dados.', DATE_ADD(CURDATE(), INTERVAL 1 DAY), 0, 3),
('Treinamento sobre a nova versão do framework', 'Participar do treinamento online sobre as novidades do PHP 8.2.', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 1, 1),
('Analisar logs de erro em produção', 'Investigar a causa do erro 500 que ocorreu ontem à noite.', DATE_ADD(CURDATE(), INTERVAL 1 DAY), 0, 2),
('Planejar a migração do servidor de banco de dados', 'Definir os passos e o cronograma para a migração do MySQL 5.7 para o 8.0.', DATE_ADD(CURDATE(), INTERVAL 30 DAY), 0, 3),
('Desenvolver funcionalidade de busca avançada', 'Permitir que usuários filtrem produtos por categoria, preço e marca.', DATE_ADD(CURDATE(), INTERVAL 25 DAY), 0, 1),
('Melhorar a acessibilidade do site (WCAG)', 'Ajustar o contraste das cores e adicionar atributos ARIA nos componentes.', DATE_ADD(CURDATE(), INTERVAL 13 DAY), 0, 2),
('Criar um script de backup automático do banco de dados', 'O script deve rodar diariamente e salvar o backup em um storage externo.', DATE_ADD(CURDATE(), INTERVAL 7 DAY), 1, 3),
('Configurar CI/CD para o projeto', 'Automatizar o processo de build, teste e deploy usando Jenkins ou GitHub Actions.', DATE_ADD(CURDATE(), INTERVAL 22 DAY), 0, 1),
('Realizar entrevista técnica com candidato', 'Entrevistar candidato para a vaga de Desenvolvedor Back-End Pleno.', DATE_ADD(CURDATE(), INTERVAL 3 DAY), 1, 2),
('Estudar sobre arquitetura de microsserviços', 'Ler artigos e assistir a vídeos sobre os prós e contras de microsserviços.', DATE_ADD(CURDATE(), INTERVAL 16 DAY), 0, 3),
('Desenvolver a página de perfil do usuário', 'A página deve exibir as informações do usuário e suas últimas atividades.', DATE_ADD(CURDATE(), INTERVAL 10 DAY), 1, 1),
('Ajustar o alinhamento dos ícones no rodapé', 'Os ícones das redes sociais não estão centralizados corretamente.', DATE_ADD(CURDATE(), INTERVAL 1 DAY), 0, 2),
('Criar a política de privacidade da aplicação', 'Redigir o texto da política de privacidade de acordo com a LGPD.', DATE_ADD(CURDATE(), INTERVAL 8 DAY), 1, 3),
('Implementar login com Google e Facebook', 'Adicionar botões de login social na página de autenticação.', DATE_ADD(CURDATE(), INTERVAL 17 DAY), 0, 1),
('Monitorar o consumo de CPU do servidor', 'Analisar os picos de uso de CPU após o último deploy.', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 0, 2),
('Corrigir a validação do campo de data de nascimento', 'O campo não está aceitando datas válidas em alguns cenários.', DATE_ADD(CURDATE(), INTERVAL 4 DAY), 0, 3),
('Participar da reunião diária (daily stand-up)', 'Sincronizar com a equipe sobre o andamento das tarefas.', DATE_ADD(CURDATE(), INTERVAL 1 DAY), 1, 1),
('Criar a landing page para a nova campanha de marketing', 'Desenvolver a página com o formulário de inscrição para o webinar.', DATE_ADD(CURDATE(), INTERVAL 6 DAY), 0, 2),
('Configurar o sistema de logs centralizado (ELK)', 'Enviar os logs da aplicação para o Elasticsearch.', DATE_ADD(CURDATE(), INTERVAL 28 DAY), 0, 3),
('Remover código legado do módulo de faturamento', 'Refatorar e remover funções e classes que não são mais utilizadas.', DATE_ADD(CURDATE(), INTERVAL 19 DAY), 0, 1),
('Testar o envio de emails em diferentes provedores', 'Verificar se os emails estão sendo entregues corretamente no Gmail, Outlook e outros.', DATE_ADD(CURDATE(), INTERVAL 5 DAY), 1, 2),
('Atualizar o manual do usuário', 'Adicionar a documentação das novas funcionalidades desenvolvidas na última sprint.', DATE_ADD(CURDATE(), INTERVAL 14 DAY), 0, 3),
('Definir as métricas de performance (KPIs) do sistema', 'Escolher as principais métricas para monitorar a saúde da aplicação.', DATE_ADD(CURDATE(), INTERVAL 9 DAY), 1, 1),
('Gerar relatório de vendas do último trimestre', 'Extrair os dados e montar o relatório para a diretoria.', DATE_ADD(CURDATE(), INTERVAL 3 DAY), 0, 2),
('Desenvolver endpoint para exportação de usuários em CSV', 'O endpoint deve ser acessível apenas para administradores.', DATE_ADD(CURDATE(), INTERVAL 12 DAY), 0, 3),
('Aplicar patch de segurança no servidor web', 'Atualizar o Apache para a última versão para corrigir a vulnerabilidade recém-descoberta.', DATE_ADD(CURDATE(), INTERVAL 1 DAY), 0, 1),
('Ajustar o tamanho da fonte na tabela de preços', 'A fonte está muito pequena em dispositivos móveis.', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 1, 2),
('Revisar a tradução para o idioma espanhol', 'Validar as strings traduzidas para a interface em espanhol.', DATE_ADD(CURDATE(), INTERVAL 7 DAY), 0, 3),
('Criar um protótipo para o novo dashboard', 'Desenhar um protótipo de baixa fidelidade da nova tela de dashboard.', DATE_ADD(CURDATE(), INTERVAL 11 DAY), 0, 1),
('Otimizar o tamanho das imagens do site', 'Comprimir as imagens para melhorar o tempo de carregamento das páginas.', DATE_ADD(CURDATE(), INTERVAL 4 DAY), 1, 2),
('Implementar two-factor authentication (2FA)', 'Adicionar uma camada extra de segurança no login com 2FA via app.', DATE_ADD(CURDATE(), INTERVAL 24 DAY), 0, 3),
('Corrigir problema de concorrência no carrinho de compras', 'Evitar que o estoque fique negativo quando dois usuários compram o mesmo item simultaneamente.', DATE_ADD(CURDATE(), INTERVAL 8 DAY), 0, 1),
('Migrar o projeto para a nova versão do PHP', 'Atualizar o código para ser compatível com o PHP 8.3.', DATE_ADD(CURDATE(), INTERVAL 40 DAY), 0, 2),
('Desenvolver o sistema de gamificação', 'Criar sistema de pontos e medalhas para usuários engajados.', DATE_ADD(CURDATE(), INTERVAL 35 DAY), 0, 3),
('Configurar alerta de performance', 'Receber notificação quando o tempo de resposta da API exceder 500ms.', DATE_ADD(CURDATE(), INTERVAL 5 DAY), 1, 1),
('Analisar e escolher um novo provedor de e-mail transacional', 'Comparar SendGrid, Mailgun e Amazon SES.', DATE_ADD(CURDATE(), INTERVAL 13 DAY), 0, 2),
('Criar a página "Sobre Nós"', 'Adicionar informações sobre a equipe e a história da empresa.', DATE_ADD(CURDATE(), INTERVAL 6 DAY), 0, 3),
('Implementar paginação na lista de clientes', 'Exibir 20 clientes por página para melhorar a performance.', DATE_ADD(CURDATE(), INTERVAL 9 DAY), 1, 1),
('Realizar teste de carga na aplicação', 'Simular 1000 usuários simultâneos para verificar a capacidade do servidor.', DATE_ADD(CURDATE(), INTERVAL 21 DAY), 0, 2),
('Refatorar CSS para usar BEM', 'Converter o CSS existente para a metodologia BEM para melhor organização.', DATE_ADD(CURDATE(), INTERVAL 26 DAY), 0, 3),
('Corrigir bug de cálculo de frete', 'O frete está sendo calculado incorretamente para a região Norte.', DATE_ADD(CURDATE(), INTERVAL 3 DAY), 0, 1),
('Agendar reunião de retrospectiva da Sprint', 'Marcar a reunião com a equipe para discutir os pontos positivos e negativos da sprint.', DATE_ADD(CURDATE(), INTERVAL 1 DAY), 1, 2),
('Criar documentação para o processo de onboarding de novos devs', 'Descrever o passo a passo para configurar o ambiente de desenvolvimento.', DATE_ADD(CURDATE(), INTERVAL 15 DAY), 0, 3),
('Implementar a funcionalidade "Lembrar de mim"', 'Manter o usuário logado entre as sessões.', DATE_ADD(CURDATE(), INTERVAL 10 DAY), 1, 1),
('Atualizar a logo da empresa no site', 'Substituir a logo antiga pela nova versão em todas as páginas.', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 0, 2),
('Pesquisar sobre "clean architecture"', 'Entender os conceitos de arquitetura limpa para aplicar no projeto.', DATE_ADD(CURDATE(), INTERVAL 18 DAY), 0, 3),
('Desenvolver o CRUD de categorias', 'Criar a interface e a lógica para gerenciar as categorias de produtos.', DATE_ADD(CURDATE(), INTERVAL 12 DAY), 0, 1),
('Ajustar o fuso horário da aplicação', 'Garantir que todas as datas sejam salvas e exibidas no fuso horário correto (UTC).', DATE_ADD(CURDATE(), INTERVAL 4 DAY), 1, 2),
('Criar um script para anonimização de dados', 'Gerar uma versão anonimizada do banco de dados para o ambiente de desenvolvimento.', DATE_ADD(CURDATE(), INTERVAL 17 DAY), 0, 3),
('Implementar dark mode na interface', 'Permitir que o usuário escolha entre o tema claro e escuro.', DATE_ADD(CURDATE(), INTERVAL 23 DAY), 0, 1),
('Revisar e aprovar as despesas do time', 'Validar os relatórios de despesas enviados pela equipe no sistema interno.', DATE_ADD(CURDATE(), INTERVAL 3 DAY), 0, 2),
('Configurar um firewall para o servidor', 'Limitar o acesso a portas e IPs para aumentar a segurança.', DATE_ADD(CURDATE(), INTERVAL 8 DAY), 1, 3),
('Corrigir o link quebrado na página de ajuda', 'O link para a documentação externa está retornando 404.', DATE_ADD(CURDATE(), INTERVAL 1 DAY), 0, 1),
('Otimizar a importação de planilhas', 'Melhorar a performance do processo de importação de arquivos .xlsx com muitos dados.', DATE_ADD(CURDATE(), INTERVAL 20 DAY), 0, 2),
('Planejar a arquitetura do novo módulo de chat', 'Definir as tecnologias (e.g., WebSockets) e a estrutura do chat em tempo real.', DATE_ADD(CURDATE(), INTERVAL 27 DAY), 0, 3),
('Criar a página de termos de serviço', 'Elaborar o conteúdo dos termos de uso da plataforma.', DATE_ADD(CURDATE(), INTERVAL 11 DAY), 1, 1),
('Realizar workshop sobre testes de software', 'Apresentar para a equipe as melhores práticas em testes unitários e de integração.', DATE_ADD(CURDATE(), INTERVAL 16 DAY), 0, 2),
('Validar o formulário de contato', 'Adicionar validação de e-mail e campo de mensagem obrigatório.', DATE_ADD(CURDATE(), INTERVAL 4 DAY), 0, 3),
('Implementar um sistema de feature flags', 'Permitir ligar e desligar funcionalidades em produção sem a necessidade de deploy.', DATE_ADD(CURDATE(), INTERVAL 29 DAY), 0, 1),
('Atualizar o certificado SSL do domínio', 'Renovar o certificado SSL antes que ele expire no próximo mês.', DATE_ADD(CURDATE(), INTERVAL 19 DAY), 0, 2),
('Corrigir a ordenação da tabela de usuários', 'A tabela não está ordenando corretamente pela coluna de data de cadastro.', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 0, 3),
('Desenvolver a tela de configurações do perfil', 'Permitir que o usuário altere seu nome, e-mail e senha.', DATE_ADD(CURDATE(), INTERVAL 14 DAY), 1, 1),
('Analisar a viabilidade de usar um framework front-end', 'Estudar a possibilidade de adotar Vue.js ou React no projeto.', DATE_ADD(CURDATE(), INTERVAL 25 DAY), 0, 2),
('Criar a rotina de envio de newsletter semanal', 'Desenvolver o script que envia as novidades da semana para os usuários cadastrados.', DATE_ADD(CURDATE(), INTERVAL 10 DAY), 0, 3),
('Ajustar permissões de acesso dos usuários', 'Garantir que usuários "leitores" não possam editar ou excluir registros.', DATE_ADD(CURDATE(), INTERVAL 7 DAY), 1, 1),
('Integrar com a API de CEP dos Correios', 'Preencher automaticamente o endereço a partir do CEP informado.', DATE_ADD(CURDATE(), INTERVAL 9 DAY), 0, 2),
('Remover jQuery do projeto', 'Substituir todas as funcionalidades que usam jQuery por JavaScript puro (vanilla JS).', DATE_ADD(CURDATE(), INTERVAL 33 DAY), 0, 3),
('Documentar o processo de deploy em produção', 'Criar um guia passo a passo para realizar o deploy de forma segura.', DATE_ADD(CURDATE(), INTERVAL 13 DAY), 0, 1),
('Corrigir o fuso horário no agendamento de relatórios', 'Os relatórios agendados estão sendo gerados com 3 horas de diferença.', DATE_ADD(CURDATE(), INTERVAL 3 DAY), 0, 2),
('Melhorar a mensagem de erro na tela de login', 'Exibir uma mensagem mais clara para o usuário em caso de falha na autenticação.', DATE_ADD(CURDATE(), INTERVAL 2 DAY), 1, 3),
('Criar a funcionalidade de "favoritar" itens', 'Permitir que os usuários marquem seus produtos preferidos.', DATE_ADD(CURDATE(), INTERVAL 18 DAY), 0, 1),
('Testar a compatibilidade com o navegador Safari', 'Verificar e corrigir problemas de layout e funcionalidade no Safari.', DATE_ADD(CURDATE(), INTERVAL 8 DAY), 0, 2),
('Configurar a rotação de logs (log rotation)', 'Evitar que os arquivos de log consumam todo o espaço em disco.', DATE_ADD(CURDATE(), INTERVAL 6 DAY), 1, 3),
('Desenvolver o widget de "últimas notícias" para o dashboard', 'O widget deve exibir os 5 posts mais recentes do blog.', DATE_ADD(CURDATE(), INTERVAL 11 DAY), 0, 1),
('Fazer a apresentação do balanço do projeto', 'Apresentar os resultados e aprendizados do último trimestre para a gestão.', DATE_ADD(CURDATE(), INTERVAL 5 DAY), 0, 2),
('Estudar a implementação de um message broker (RabbitMQ)', 'Analisar como usar filas para processar tarefas assíncronas e pesadas.', DATE_ADD(CURDATE(), INTERVAL 22 DAY), 0, 3),
('Criar o instalador da aplicação', 'Desenvolver um script (wizard) que facilite a instalação da aplicação em novos ambientes.', DATE_ADD(CURDATE(), INTERVAL 38 DAY), 0, 1),
('Atualizar a biblioteca de ícones (Font Awesome)', 'Migrar da versão 4 para a 6 para ter acesso a novos ícones.', DATE_ADD(CURDATE(), INTERVAL 9 DAY), 0, 2),
('Corrigir a exportação de PDF que não inclui imagens', 'As imagens dos produtos não estão sendo exibidas no PDF gerado.', DATE_ADD(CURDATE(), INTERVAL 4 DAY), 0, 3),
('Realizar uma prova de conceito (PoC) com um novo ORM', 'Testar o Doctrine ou o Eloquent em um módulo isolado para avaliar a produtividade.', DATE_ADD(CURDATE(), INTERVAL 28 DAY), 0, 1);

